<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EventLens.Worker-1d1a2356-4779-4095-96cf-0f44a2525d8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventLens.Core\EventLens.Core.csproj" />
    <ProjectReference Include="..\EventLens.Persistence\EventLens.Persistence.csproj" />
    <ProjectReference Include="..\EventLens.Windows\EventLens.Windows.csproj" />
  </ItemGroup>
</Project>
